core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('our-work/', views.ourWork, name='ourWork'),
    path('our-services/', views.ourServices, name='ourServices'),
    path('<int:service_id>/service/', views.serviceDetail, name='serviceDetail'),
    path('<int:work_id>/project/', views.projectDetail, name='projectDetail'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contactUs, name='contactUs'),
    
]

youandmedesigners/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.


class Home(models.Model):
    banner_image = models.ImageField(blank=True,null=True)
    banner_area_text = models.TextField(blank=True,null=True)
    logo = models.ImageField(blank=True,null=True)
    services_title = models.CharField(max_length=100,blank=True,null=True)
    services_description = models.CharField(max_length=200,blank=True,null=True)
    services_desc_large = models.TextField(blank=True,null=True)
    work_title = models.CharField(max_length=100,blank=True,null=True)
    work_description = models.CharField(max_length=200,blank=True,null=True)
    work_desc_large = models.TextField(blank=True,null=True)
    our_address = models.CharField(max_length=500,blank=True,null=True)
    our_phone =  models.CharField(max_length=500,blank=True,null=True)
    our_mail = models.CharField(max_length=500,blank=True,null=True)
    about_us = models.TextField(blank=True,null=True)



class OurServices(models.Model):
    img = models.ImageField(blank=True,null=True)
    heading = models.CharField(max_length=20)
    short_content = models.CharField(max_length=150)
    content = models.TextField()

class OurWork(models.Model):
    img = models.ImageField(blank=True,null=True)
    ratings = models.IntegerField(blank=True,null=True)
    client = models.CharField(max_length=100,blank=True,null=True)
    client_website = models.CharField(max_length=100,blank=True,null=True)
    completed = models.DateTimeField(blank=True,null=True)
    title = models.CharField(max_length=20)
    short_content = models.CharField(max_length=150)
    content = models.TextField()

class Gallery(models.Model):
    image = models.ImageField()

class Contact(models.Model):
    name = models.CharField(max_length=500,blank=True,null=True)
    phone = models.CharField(max_length=500,blank=True,null=True)
    email = models.CharField(max_length=500,blank=True,null=True)
    description = models.CharField(max_length=500,blank=True,null=True)

class Blog(models.Model):
    title = models.CharField(max_length=200,blank=True,null=True)
    short_desc = models.CharField(max_length=200,blank=True,null=True)
    description = models.TextField()
    published_date = models.DateTimeField()
    viewss = models.IntegerField(default=0)
    image = models.ImageField()

core/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect, reverse
from core.models import Home,OurServices,OurWork,Contact,Blog,Gallery
# Create your views here.


def home(request):
    a = Home.objects.get(id=1)
    services = OurServices.objects.all()[:3]
    projects = OurWork.objects.all()[:8] 
    blogs = Blog.objects.all()[:3]  

    context= {
        "home_banner":a.banner_area_text,
        "services_title":a.services_title,
        "services_description":a.services_description,
        "work_title":a.work_title,
        "work_description":a.work_description,
        "services":services,
        "projects":projects,
        "blogs":blogs       

    }
    return render(request, 'core/index.html',context=context)


def about(request):
    a = Home.objects.get(id=1)
    projects = OurWork.objects.all()[:8] 
    context = {
        "about_us":a.about_us,
        "work_title":a.work_title,
        "work_description":a.work_description,
        "projects":projects,

    }
    return render(request, 'core/about-us.html',context=context)


def ourWork(request):
    a = Home.objects.get(id=1)
    projects = OurWork.objects.all()[:8] 
    context = {
        "about_us":a.about_us,
        "work_title":a.work_title,
        "work_description":a.work_description,
        "projects":projects,

    }
    return render(request, 'core/projects.html',context=context)


def ourServices(request):
    a = Home.objects.get(id=1)
    services = OurServices.objects.all()
    projects = OurWork.objects.all()[:8] 
    context= {
        "services_title":a.services_title,
        "services_description":a.services_description,
        "work_title":a.work_title,
        "work_description":a.work_description,
        "projects":projects,        
        "services_title":a.services_title,
        "services_description":a.services_description,       
        "services":services,
           

    }
    return render(request, 'core/services.html',context=context)

def serviceDetail(request,service_id):
   
    service = OurServices.objects.get(id=service_id)
    
    context= {
        "service":service

    }
    return render(request, 'core/service-details.html',context=context)

def projectDetail(request,work_id):
       
    service = OurWork.objects.get(id=work_id)
    
    context= {
        "service":service

    }
    return render(request, 'core/project-details.html',context=context)

def gallery(request):
    a =Gallery.objects.all()
    context = {
        "gallery":a
    }
    return render(request, 'core/gallery.html',context=context)
    

def contactUs(request):
    if request.method == "POST":
        c = Contact()        
        c.name = request.POST["name"]
        c.phone = request.POST["phone"]
        c.email = request.POST["email"]
        c.description = request.POST["message"]
        c.save()

    a = Home.objects.get(id=1)
    
    context= {
       'detail':a   

    }
    return render(request, 'core/contact.html',context=context)

templates/base/header.html
<!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="main_menu" id="mainNav">
            	<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container box_1620">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav ml-auto">
								<li class="nav-item"><a class="nav-link" href="{% url 'core:home' %}">Home</a></li> 
								<li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About</a></li> 
								<li class="nav-item"><a class="nav-link" href="{% url 'core:ourWork' %}">Our Work</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'core:ourServices' %}">Services</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'core:gallery' %}">Gallery</a></li>
                                {% comment %} <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li> {% endcomment %}
								{% comment %} <li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="project-details.html">Project Details</a></li>
										<li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
									</ul>
								</li> 
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
										<li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
									</ul>
								</li>  {% endcomment %}
								<li class="nav-item"><a class="nav-link" href="{% url 'core:contactUs' %}">Contact</a></li>
							</ul>
						</div> 
					</div>
            	</nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->

templates/core/about-us.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>About Us</h2>
						<div class="page_link">
							<a href="{% url 'core:home' %}">Home</a>
							<a href="{% url 'core:about' %}">About Us</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

		<section class="sample-text-area">
				<div class="container">
					{{ about_us|safe }}
					
				</div>
			</section>

			 <!--================Post Slider Area =================-->
        <section class="post_slider_area">
        	<div class="main_title">
				<h2>{{ work_title|safe }}</h2>
				<p>{{ work_description|safe }}</p>
			</div>
			<div class="post_slider_inner owl-carousel">
			{% for each in projects %}
				<div class="item">
					<div class="post_s_item">
						<div class="post_img">
							<img src={{ each.img.url}} alt="">
						</div>
						<div class="post_text">
							<a href="single-blog.html"><h4>{{each.title}}</h4></a>
							<p>{{each.short_content}}</p>
							<a class="main_btn" href="#">View Details</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
        </section>
        <!--================End Post Slider Area =================-->
		<br>
		<br>
        
       
       
        
      {% endblock %}

templates/core/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="img/favicon.png" type="image/png">
        <title>youandmedesigners</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="css/bootstrap.css">
        <link rel="stylesheet" href="vendors/linericon/style.css">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="vendors/owl-carousel/owl.carousel.min.css">
        <link rel="stylesheet" href="vendors/lightbox/simpleLightbox.css">
        <link rel="stylesheet" href="vendors/nice-select/css/nice-select.css">
        <link rel="stylesheet" href="vendors/animate-css/animate.css">
        <!-- main css -->
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/responsive.css">
    </head>
    <body>
    

templates/core/gallery.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Gallery</h2>
						<div class="page_link">
							<a href="{% url 'core:home' %}">Home</a>
							<a href="{% url 'core:gallery' %}">Image Gallery</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <div class="whole-wrap">
				<div class="container">
     
					<div class="section-top-border">
						<h3 class="title_color">Image Gallery</h3>
						<div class="row gallery-item">
						{% for each in gallery %}
						
						
						<div class="col-md-3">
								<a href="{{ each.image.url }}" class="img-gal"><div class="single-gallery-image" style="background: url({{ each.image.url }});"></div></a>
							</div>
						
						
						
						{% endfor %}
							
							
						</div>
					</div>
					</div>
					</div>
					
        
    {% endblock %}

templates/core/index.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

        
     <!--================Home Banner Area =================-->
        <section class="home_banner_area" id="home">
            <div class="banner_inner">
				<div class="container">
					<div class="banner_content">
						{{ home_banner|safe }}
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <br>
        
	

        <!--================Feature Area =================-->
        <section class="feature_area">
        	<div class="container">
        		<div class="main_title">
        			<h2>{{ services_title|safe }}</h2>
        			<p>{{ services_description|safe }}/p>
        		</div>
        		<div class="feature_inner row">
				{% for each in services%}
        			<div class="col-lg-4">
        				<div class="feature_item">
        					<img src={{ each.img.url }} alt="">
        					<h4>{{each.heading}}</h4>
        					<p>{{each.short_content}}</p>
        					<a class="main_btn" href="{% url 'core:serviceDetail' each.id %}">View Details</a>
        				</div>
        			</div>
					 {% endfor %}
      
        		</div>
        	</div>
        </section>
        <!--================End Feature Area =================-->
        
        <!--================Post Slider Area =================-->
        <section class="post_slider_area">
        	<div class="main_title">
				<h2>{{ work_title|safe }}</h2>
				<p>{{ work_description|safe }}</p>
			</div>
			<div class="post_slider_inner owl-carousel">
			{% for each in projects %}
				<div class="item">
					<div class="post_s_item">
						<div class="post_img">
							<img src={{ each.img.url}} alt="">
						</div>
						<div class="post_text">
							<a href="single-blog.html"><h4>{{each.title}}</h4></a>
							<p>{{each.short_content}}</p>
							<a class="main_btn" href="{% url 'core:projectDetail' each.id %}">View Details</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
        </section>
        <!--================End Post Slider Area =================-->
        
        {% comment %} <!--================Testimonials Area =================-->
        <section class="testimonials_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>What Customer Say About Us</h2>
        			<p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.</p>
        		</div>
        		<div class="testi_slider owl-carousel">
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-1.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-2.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-1.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-2.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-1.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        			<div class="item">
        				<div class="testi_item">
							<div class="media">
								<div class="d-flex">
									<img src="img/testimonials/testi-2.png" alt="">
								</div>
								<div class="media-body">
									<p>Accessories Here you can find the best computer accessory for your laptop, monitor, printer, scanner, speaker, projector, hardware.</p>
									<h4>Mark Alviro Wiens</h4>
									<div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
								</div>
							</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Testimonials Area =================-->
        
        <!--================Clients Logo Area =================-->
        <section class="clients_logo_area p_120">
        	<div class="container">
        		<div class="clients_slider owl-carousel">
        			<div class="item">
        				<img src="img/clients-logo/c-logo-1.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-2.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-3.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-4.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-5.png" alt="">
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Clients Logo Area =================--> {% endcomment %}
        

        <!--================Our Blog Area =================-->
        <section class="our_blog_area p_120">
        	<div class="container">
        		<div class="main_title">
        			<h2>Recent From Our Blog</h2>
        		</div>
        		<div class="blog_inner row">
				{% for each in blogs %}
        			
        			<div class="col-lg-4">
        				<div class="o_blog_item">
        					<div class="blog_img">
        						<img class="img-fluid" src={{ each.image.url }} alt="">
        					</div>
        					<div class="blog_text">
        						
        						<a href="#"><h4>{{ each.title }}</h4></a>
        						<p>{{each.short_desc}}</p>
        						<a class="date" href="#">{{each.published_date}}</a>
        					</div>
        				</div>
        			</div>
					{% endfor %}
        			
        		</div>
        	</div>
        </section>
        <!--================End Our Blog Area =================-->
        
 {% endblock %}

templates/core/project-details.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Project Details</h2>
						<div class="page_link">
							<a href="{% url 'core:home' %}">Home</a>
							<a href="{% url 'core:ourWork' %}">Projects</a>
							<a href="#">Project Details</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
    

        <!--================Portfolio Details Area =================-->
        <section class="portfolio_details_area p_120">
        	<div class="container">
        		<div class="portfolio_details_inner">
					<div class="row">
						<div class="col-md-6">
							<div class="left_img">
								<img class="img-fluid" src="{{ service.img.url }}"  alt="">
							</div>
						</div>
						<div class="col-md-6">
							<div class="portfolio_right_text">
								<h4>{{service.title}}</h4>
								<p>{{service.short_content}}</p>
								<ul class="list">
									<li><span>Rating</span>: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></li>
									<li><span>Client</span>: {{service.client}}</li>
									<li><span>Website</span>:  {{service.client_website}}</li>
									<li><span>Completed</span>:  {{service.completed}}</li>
								</ul>
								<ul class="list social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-behance"></i></a></li>
									<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
					{{ service.content|safe }}

        		</div>
        	</div>
        </section>
        <!--================End Portfolio Details Area =================-->
        
        <!--================Clients Logo Area =================-->
        <section class="clients_logo_area p_120">
        	<div class="container">
        		<div class="clients_slider owl-carousel">
        			<div class="item">
        				<img src="img/clients-logo/c-logo-1.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-2.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-3.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-4.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-5.png" alt="">
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Clients Logo Area =================-->
        
 {% endblock %}

templates/core/projects.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Projects</h2>
						<div class="page_link">
							<a href="{% url 'core:home' %}">Home</a>
							<a href="{% url 'core:ourWork' %}">Projects</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
		<br><br><br><br>        
        <!--================Post Slider Area =================-->
        <section class="post_slider_area">
        	<div class="main_title">
				<h2>{{ work_title|safe }}</h2>
				<p>{{ work_description|safe }}</p>
			</div>
			<div class="post_slider_inner owl-carousel">
			{% for each in projects %}
				<div class="item">
					<div class="post_s_item">
						<div class="post_img">
							<img src={{ each.img.url}} alt="">
						</div>
						<div class="post_text">
							<a href="single-blog.html"><h4>{{each.title}}</h4></a>
							<p>{{each.short_content}}</p>
							<a class="main_btn" href="{% url 'core:projectDetail' each.id %}">View Details</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
        </section>
        <!--================End Post Slider Area =================-->
		<br>
		<br>
       
        
        {% comment %} <!--================Clients Logo Area =================-->
        <section class="clients_logo_area p_120">
        	<div class="container">
        		<div class="clients_slider owl-carousel">
        			<div class="item">
        				<img src="img/clients-logo/c-logo-1.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-2.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-3.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-4.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-5.png" alt="">
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Clients Logo Area =================-->
         {% endcomment %}
        {% endblock %}

templates/core/services.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Services</h2>
						<div class="page_link">
							<a href="{% url 'core:home' %}">Home</a>
							<a href="{% url 'core:ourServices' %}">Services</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Feature Area =================-->
				<br>
        <section class="feature_area">
        	<div class="container">
        		<div class="main_title">
        			<h2>{{ services_title|safe }}</h2>
        			<p>{{ services_description|safe }}/p>
        		</div>
        		<div class="feature_inner row">
				{% for each in services%}
        			<div class="col-lg-4">
        				<div class="feature_item">
        					<img src={{ each.img.url }} alt="">
        					<h4>{{each.heading}}</h4>
        					<p>{{each.short_content}}</p>
        					<a class="main_btn" href="{% url 'core:serviceDetail' each.id %}">View Details</a>
        				</div>
        			</div>
					 {% endfor %}
      
        		</div>
        	</div>
        </section>
        <!--================End Feature Area =================-->
        
        <!--================Post Slider Area =================-->
          <section class="post_slider_area">
        	<div class="main_title">
				<h2>{{ work_title|safe }}</h2>
				<p>{{ work_description|safe }}</p>
			</div>
			<div class="post_slider_inner owl-carousel">
			{% for each in projects %}
				<div class="item">
					<div class="post_s_item">
						<div class="post_img">
							<img src={{ each.img.url}} alt="">
						</div>
						<div class="post_text">
							<a href="single-blog.html"><h4>{{each.title}}</h4></a>
							<p>{{each.short_content}}</p>
							<a class="main_btn" href="{% url 'core:projectDetail' each.id %}">View Details</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
        </section>
        <!--================End Post Slider Area =================-->
        
        <!--================Clients Logo Area =================-->
        <section class="clients_logo_area p_120">
        	<div class="container">
        		<div class="clients_slider owl-carousel">
        			<div class="item">
        				<img src="img/clients-logo/c-logo-1.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-2.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-3.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-4.png" alt="">
        			</div>
        			<div class="item">
        				<img src="img/clients-logo/c-logo-5.png" alt="">
        			</div>
        		</div>
        	</div>
        </section>
        <!--================End Clients Logo Area =================-->
        
      
        
        
{% endblock %}